# vim ft=yaml
# travis-ci.org definition for tclclockmod build
# https://travis-ci.org/sebres/tclclockmod/
dist: trusty
sudo: true

language: c

matrix:
  fast_finish: true

  include:
### Linux-builds:
    - os: linux
      compiler: gcc
      env:
        - BUILD_TRG_DIR=unix
        - CFGOPT=""
    - os: linux
      compiler: clang
      env:
        - BUILD_TRG_DIR=unix
        - CFGOPT=""
### Mingw cross-compile build:
### # C builds not currently supported on Windows instances
#    - os: windows
#      env:
#        - BUILD_TRG_DIR=win
### # ... so proxy with a Mingw cross-compile
# Test with mingw-w64 (32 bit)
    - os: linux
      dist: trusty
      compiler: i686-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - gcc-mingw-w64
            - gcc-multilib
            - wine
      env:
        - BUILD_TRG_DIR=win
        - CFGOPT="--host=i686-w64-mingw32 --disable-wince"
        - NO_DIRECT_TEST=1
# Test with mingw-w64 (64 bit)
    - os: linux
      dist: trusty
      compiler: x86_64-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - gcc-mingw-w64
            - wine
      env:
        - BUILD_TRG_DIR=win
        - CFGOPT="--host=x86_64-w64-mingw32 --enable-64bit --disable-wince"
        - NO_DIRECT_TEST=1

addons:
  apt:
    packages:
      #- tcl8.6
      #- tcl8.6-dev

before_script:
  # ATM trusty has too old tcl version (8.6.0), thus install newest 8.6.7 ...
  - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ artful main universe"
  - sudo apt-get update
  - sudo apt-get install -t artful -y tcl8.6 tcl8.6-dev
  # show version:
  - echo puts [info patchlevel] | tclsh
  - export BUILD_DIR=$(pwd)
  # prerequirements (tclconfig)
  - git clone https://github.com/tcltk/tclconfig.git ./tclconfig

script:
  - echo "Build with $CC ..."
  #- autoconf
  #- autoreconf -iv
  - cd $BUILD_TRG_DIR
  - ../configure --with-tcl=/usr/lib/tcl8.6 ${CFGOPT}
  - make

  # current time and time-zone:
  - echo $TZ; timedatectl status
  # if can test
  - |
    if [ "$NO_DIRECT_TEST" != 1 ]; then
      # load local library and execute local test cases:
      tclsh $BUILD_DIR/tests/all.tcl
    fi

  # test install:
  - |
    if [ "$NO_DIRECT_TEST" != 1 ]; then
      sudo make install
      echo 'if {[catch {package require tclclockmod; clock format -now}]} {puts stderr "ERROR!"; exit 1} else {puts "OK."}' | tclsh
    fi

  # clean all
  - make clean
